### ISSUE TITLE
能自定义类型么

### ISSUE THREAD

**Issue by agileago** [RmondJone/Commit-Message-Plugin#1]

**Comment by KANLON** [comment]
+1,好像类型换成英文比较好？之前  阮一峰 大佬写的一篇博客，是用英文的，https://www.ruanyifeng.com/blog/2016/01/commit_message_change_log.html

**Comment by RmondJone** [comment]
有考虑过，这个问题，但是觉得没得必要，也就那么多提交类型，你可以找找另一个，有个可以自己在设置里加类型
