### ISSUE TITLE
插件用不了  纸飞机不弹窗

### ISSUE THREAD

**Issue by nixi512** [RmondJone/Commit-Message-Plugin#11]
在other settings里面的commit message create插件界面显示select configuration element in the tree to edit its settings；但是里面的其他插件就都有界面显示设置，idea也非汉化版

**Comment by RmondJone** [comment]
还有报错日志或者截图，描述比较抽象，一时没有理解

**Comment by nixi512** [comment]
感谢大牛




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年6月1日(星期三) 下午4:14
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [RmondJone/Commit-Message-Plugin] 插件用不了  纸飞机不弹窗 (Issue #11)





 Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0     
本地JAVA环境问题，好像JDK1.8调用不起来，需要使用JDK 11。回头我看下能不能兼容

**Comment by RmondJone** [comment]
兼容到了2019.1，你IDE太老了，兄弟可以升级了

**Comment by nixi512** [comment]
哈哈哈，准备换成2020.3的用用
