### ISSUE TITLE
UI交互是否可以优化一下？

### ISSUE THREAD

**Issue by MarxZhou** [RmondJone/Commit-Message-Plugin#12]
<img width="799" alt="image" src="https://user-images.githubusercontent.com/39861054/182751476-c9d50d45-9135-478b-a401-44cdd9f49c00.png">

1、提交类型这个下拉选择框改成从上到下排列的单选按钮组，局部可以滚动
2、修改版本号右侧的历史按钮功能改成下拉列表

可以参考一下插件“Git Commit Template”的设计：
<img width="880" alt="image" src="https://user-images.githubusercontent.com/39861054/182752179-0e43840a-d6b8-4e74-a2f8-abbe6487144d.png">

**Comment by RmondJone** [comment]
感觉这个不是优化，是负优化。。。
