### ISSUE TITLE
我对模版做了修改适应项目实际情况，那么我现在如何方便将自己编辑好的模版导给项目其他成员呢

### ISSUE THREAD

**Issue by imcloud** [RmondJone/Commit-Message-Plugin#14]
我对模版做了修改适应项目实际情况，那么我现在如何方便将自己编辑好的模版导给项目其他成员呢

**Comment by RmondJone** [comment]
> 我对模版做了修改适应项目实际情况，那么我现在如何方便将自己编辑好的模版导给项目其他成员呢

这块我暂时还没有做导出，后续我做个配置导出，尽请期待。我计划近期做一版重构，新增模板导出、CHANGLOG自动生成功能。

**Comment by imcloud** [comment]
好的非常感谢
