### ISSUE TITLE
历史修改版本的缓存记录能否根据项目区分

### ISSUE THREAD

**Issue by DaiwenZh5** [RmondJone/Commit-Message-Plugin#7]
目前会直接缓存所有项目的修改版本，希望能根据项目区分，不然找半天，就不如手写了

**Comment by RmondJone** [comment]
好，明天我过去改下。

**Comment by RmondJone** [comment]
> 目前会直接缓存所有项目的修改版本，希望能根据项目区分，不然找半天，就不如手写了

已经改了，可以直接下载最近的包即可，插件市场也已经相应上传
