### ISSUE TITLE
兼容性问题：目前插件不支持2021.2版本的webstorm

### ISSUE THREAD

**Issue by MarxZhou** [RmondJone/Commit-Message-Plugin#8]
启动时会失败，如需提供更多信息，请进行说明

**Comment by RmondJone** [comment]
好的，多谢反馈，我有时间看一下

**Comment by RmondJone** [comment]
已经适配，最新包下载地址[https://github.com/RmondJone/Commit-Message-Plugin/releases/tag/1.4.0](https://github.com/RmondJone/Commit-Message-Plugin/releases/tag/1.4.0)
