### ISSUE TITLE
新版as 4.2 可以正常安装，但是无法正常调出插件。

### ISSUE THREAD

**Issue by czeall** [RmondJone/Commit-Message-Plugin#9]
作者你好：
       最近更换了Android studio版本，安装4.2版本的as之后，搜索Commit-Message-Plugin插件可以正常安装，但是安装之后发现commit 或者push代码时都调不出之前的插件窗口。求助求解决。

**Comment by RmondJone** [comment]
已经适配，最新包下载地址[https://github.com/RmondJone/Commit-Message-Plugin/releases/tag/1.4.0](https://github.com/RmondJone/Commit-Message-Plugin/releases/tag/1.4.0)
